export * from "./YogaHero";
export * from "./YogaBenefits";
export * from "./YogaTypes";
export * from "./YogaPricing";
export * from "./TransformationsCarousel";
export * from "./YogaGallery";
export * from "./YogaVideoReviews";
export * from "./CertificationsCarousel";
export * from "./YogaFinalCta";
